services:
  app-concordia-homolog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_USUARIOS_URL: ${VITE_API_USUARIOS_URL_HOMOLOG}
        VITE_API_CLIENTES_URL: ${VITE_API_CLIENTES_URL_HOMOLOG}
        VITE_API_COMUNICACOES_URL: ${VITE_API_COMUNICACOES_URL_HOMOLOG}
        VITE_API_CONTRATOS_URL: ${VITE_API_CONTRATOS_URL_HOMOLOG}
        VITE_API_PESSOAS_URL: ${VITE_API_PESSOAS_URL_HOMOLOG}
        VITE_API_CONTATOS_URL: ${VITE_API_CONTATOS_URL_HOMOLOG}
        VITE_API_RELATORIOS_URL: ${VITE_API_RELATORIOS_URL_HOMOLOG}
        VITE_WS_SERVICE_URL: ${VITE_WS_SERVICE_URL_HOMOLOG}
    image: homolog-app-concordia:latest
    container_name: app-concordia-homolog
    restart: unless-stopped
    ports:
      - "5175:80"
    environment:
      - NODE_ENV=production
    networks:
      - marshall-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  app-concordia-main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_USUARIOS_URL: ${VITE_API_USUARIOS_URL_MAIN}
        VITE_API_CLIENTES_URL: ${VITE_API_CLIENTES_URL_MAIN}
        VITE_API_COMUNICACOES_URL: ${VITE_API_COMUNICACOES_URL_MAIN}
        VITE_API_CONTRATOS_URL: ${VITE_API_CONTRATOS_URL_MAIN}
        VITE_API_PESSOAS_URL: ${VITE_API_PESSOAS_URL_MAIN}
        VITE_API_CONTATOS_URL: ${VITE_API_CONTATOS_URL_MAIN}
        VITE_API_RELATORIOS_URL: ${VITE_API_RELATORIOS_URL_MAIN}
        VITE_WS_SERVICE_URL: ${VITE_WS_SERVICE_URL_MAIN}
    image: app-concordia:latest
    container_name: app-concordia-main
    restart: unless-stopped
    ports:
      - "3175:80"
    environment:
      - NODE_ENV=production
    networks:
      - marshall-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  marshall-network:
    driver: bridge

